name: Build and publish docs

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      # TODO cache rye installation
      - name: Install rye
        run: curl -sSf https://rye-up.com/get | RYE_INSTALL_OPTION="--yes" bash
      - name: Install project and its dependencies
        run: |
          export PATH="~/.rye/shims:$PATH"
          rye sync --no-lock
      - name: Build and deploy docs
        run: |
          export PATH="~/.rye/shims:$PATH"
          rye run mkdocs gh-deploy --force
