name: Lint

on:
  workflow_call:
  pull_request:
    branches:
      - "main"

jobs:
  lint:
    name: Lint with Ruff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      # TODO cache rye installation
      - name: Install rye
        run: curl -sSf https://rye.astral.sh/get | RYE_INSTALL_OPTION="--yes" bash
      - name: Install project and its dependencies
        run: ~/.rye/shims/rye sync --all-features
      - name: Run Ruff linter
        run: ~/.rye/shims/rye run ruff check .
      - name: Run Ruff import sorter
        run: ~/.rye/shims/rye run ruff check --select I .
      - name: Run Ruff formatter
        run: ~/.rye/shims/rye run ruff format --check .
