name: Publish to PyPI

on:
  workflow_dispatch:
  release:
    types:
      - "created"

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
  test:
    name: Test
    uses: ./.github/workflows/test.yml
    secrets: inherit
  publish:
    name: Publish to PyPI
    needs: [lint, test]
    runs-on: ubuntu-latest
    environment:
      name: PyPI
      url: https://pypi.org/project/aiosalesforce
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      # TODO cache rye installation
      - name: Install rye
        run: curl -sSf https://rye-up.com/get | RYE_INSTALL_OPTION="--yes" bash
      - name: Install project and its dependencies
        run: ~/.rye/shims/rye sync --all-features
      - name: Build
        run: ~/.rye/shims/rye build
      - name: Publish
        run: ~/.rye/shims/rye publish --token ${{ secrets.PYPI_TOKEN }} --yes
