name: Test

on:
  workflow_call:
  pull_request:
    branches:
      - "main"

jobs:
  test-linux:
    name: Test on linux and generate coverage
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python-version }}"
      # TODO cache rye installation
      - name: Install rye
        run: curl -sSf https://rye-up.com/get | RYE_INSTALL_OPTION="--yes" bash
      - name: Install project and its dependencies
        run: rye sync
      - name: Run tests and generate coverage report
        run: rye run pytest
      # TODO upload coverage to codecov
  test-windows:
    name: Test on windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Install rye
        run: curl -sSf https://rye-up.com/get | RYE_INSTALL_OPTION="--yes" bash
      - name: Install project and its dependencies
        run: rye sync
      - name: Run tests and generate coverage report
        run: rye run pytest
